runtime: nodejs14
vpc_access_connector:
  name: projects/web-nangcao-300606/locations/us-central1/connectors/vpc
beta_settings:
    cloud_sql_instances: web-nangcao-300606:us-central1:postgres
env_variables:
  NODE_ENV: production
  PORT: 8080
  FE_PORT: 3001
  NUMBER_CHAPTER_PREVIEW: 1
  DEBUG: true
  DEFAULT_LIMIT: 10
  DEFAULT_OFFSET: 0
  CONFIRM_EXP: 600000
  ACCESS_TOKEN_EXPIRE: 6000000

  DB_USERNAME: postgres
  DB_PASSWORD: postgres
  DB_NAME: web
  DB_HOST: 35.193.79.70
  SOCKET_PATH: /cloudsql/web-nangcao-300606:us-central1:postgres

  REDIS_HOST: 10.43.180.235
  REDIS_PORT: 6379

  SMTP_SERVER: smtp.google.com
  SMTP_PORT1: 465
  SMTP_PORT: 587
  SMTP_USER: ndthong144.email@gmail.com
  SMTP_PASSWORD: xojcytnelqfhxmci