runtime: nodejs14
env_variables:
  PORT: 8080
  NUMBER_CHAPTER_PREVIEW: 1
  DEBUG: true

  CONFIRM_EXP: 60
  ACCESS_TOKEN_EXPIRE: 60000000

  REDIS_HOST: 127.0.0.1
  REDIS_PORT: 6379

  SMTP_SERVER: smtp.google.com
  SMTP_PORT1: 465
  SMTP_PORT: 587
  SMTP_USER: ndthong144.email@gmail.com
  SMTP_PASSWORD: xojcytnelqfhxmci