version: "3"
services:
  # server:
  #   build: .
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://admin:admin@postgres:5432/web
  #     NODE_ENV: development
  #     PORT: 3000
  #   ports:
  #     - "3000:3000"
  #   command: npm run dev
  #   volumes:
  #     - .:/app/
  #     - /app/node_modules

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: web